name: Episodes workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 0 * * SUN" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-episodes:
    name: Update this repo's README with the recent episodes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXg4HlpyrJzO68RIjijEGBA"
          max_post_count: 100
          readme_path: "./profile/README.md"
